---
- name: Install and configure openvswitch and neutron agent
  hosts: neutron-network:nova-compute
  sudo: True
  gather_facts: True
  vars:
    component: neutron
    subcomponent: openvswitch
    packages:
      - openvswitch-common
      - openvswitch-switch
      - neutron-plugin-openvswitch-agent
    services:
      - neutron-plugin-openvswitch-agent
      - openvswitch-switch
    config_files:
      - "{{ component }}.conf"
      - api-paste.ini

  tasks:

    - name: enable net.ipv4.ip_forward in sysctl
      sysctl: 
        name: net.ipv4.ip_forward 
        value: "1"
        state: present

    - name: enable net.ipv4.conf.all.forwarding in sysctl
      sysctl: 
        name: net.ipv4.conf.all.forwarding 
        value: "1"
        state: present

    - name: disable net.ipv4.conf.all.rp_filter in sysctl
      sysctl: 
        name: net.ipv4.conf.all.rp_filter 
        value: "0"
        state: present

    - name: disable net.ipv4.conf.default.rp_filter in sysctl
      sysctl: 
        name: net.ipv4.conf.default.rp_filter 
        value: "0"
        state: present

    - name: ensure {{ component }}-{{ subcomponent }} packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: "{{ component }}"
        group: "{{ component }}"
        mode: 0600
      with_items: config_files

    - name: update ovs_neutron_plugin.ini from template
      template: 
        src: templates/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini 
        dest: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini 
        owner: neutron 
        group: neutron 
        mode: 0600

    - name: make sure symlink to ovs_neutron_plugin.ini exists
      file: 
        src: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini 
        dest: /etc/neutron/plugin.ini 
        state: link

    - name: ensure OVS kernel module is loaded
      modprobe: 
        name: openvswitch
        state: present
      ignore_errors: True
      register: modprobe_result

    - name: ensure packages to build openvswitch module are installed
      apt: 
        pkg: "{{ item }}" 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - build-essential
        - dkms
        - openvswitch-datapath-dkms
        - openvswitch-datapath-source
      when: modprobe_result|failed

    - name: build openvswitch-datapath kernel module - this may take a while
      command: /usr/bin/module-assistant -i auto-install openvswitch-datapath
      when: modprobe_result|failed

    # apparently this needs a restart when the module is built...
    - name: ensure openvswitch-switch is started and enabled
      service: 
        name: openvswitch-switch 
        state: restarted 
        enabled: yes

    - name: ensure ovs internal bridge is present
      command: /usr/bin/ovs-vsctl -- --may-exist add-br br-int

    - name: ensure neutron openvswitch service is started and enabled
      service: 
        name: neutron-plugin-openvswitch-agent 
        state: restarted 
        enabled: yes

