# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  
  config.vm.define "controller" do |machine|
    machine.vm.network :private_network, ip: "10.13.0.10", 
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.10.10.10",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "controller"
    machine.vm.provider :virtualbox do |v| 
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
  end

  config.vm.define "network" do |machine|
    machine.vm.network :private_network, ip: "10.13.0.9",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.10.10.9",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "network"
    machine.vm.provider :virtualbox do |v| 
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end
  end

  config.vm.define "compute-001" do |machine|
    machine.vm.network :private_network, ip: "10.10.10.11",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "compute-001"
    machine.vm.provider :virtualbox do |v| 
      v.customize ["modifyvm", :id, "--memory", 1024]
    end
  end

end
