---
- name: Install horizon
  hosts: horizon
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure packages are installed
      apt: 
        pkg: "{{ item }}" 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items: 
        - openstack-dashboard 
        - memcached 
        - node-less
        - python-memcache

    - name: ensure ubuntu theme is removed
      apt: 
        pkg: openstack-dashboard-ubuntu-theme 
        state: absent 
        purge: yes

    - name: update memcached.conf from template
      template:
        src: templates/etc/memcached.conf
        dest: /etc/memcached.conf
        owner: root
        group: root
        mode: 0644

    - name: update local_settings.py from template
      template:
        src: templates/etc/openstack-dashboard/local_settings.py
        dest: /etc/openstack-dashboard/local_settings.py
        owner: root
        group: root
        mode: 0644
