---
- name: Configure RabbitMQ server
  hosts: rabbitmq
  sudo: True
  gather_facts: False
  tasks:

    - name: ensure heat vhost is present
      rabbitmq_vhost: 
        name: /heat
        state: present

    - name: ensure heat user is present
      rabbitmq_user: 
        user: heat
        password: "{{ heat_rabbit_password }}" 
        vhost: /heat
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        force: yes
