Vagrant::Config.run do |config|

  config.vm.box = "precise64"

  config.vm.define :controller do |controller_config|
    controller_config.vm.network :hostonly, "192.168.206.130"
  end

  config.vm.define :compute1 do |compute1_config|
    compute1_config.vm.network :hostonly, "192.168.206.131"
  end

  config.vm.define :compute2 do |compute2_config|
    compute2_config.vm.network :hostonly, "192.168.206.132"
  end

end
